name: Publish Docker image for latest release

on:
  push:
    tags:
      - release

env:
  TEST_TAG: zeek:latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      # Create and boot a loader. This will e.g., provide caching
      # so we avoid rebuilds of the same image after this step.
      - uses: docker/setup-buildx-action@v1
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: docker/Dockerfile
          # Load and tag the image so it can be used by the `test` job below.
          load: true
          tags: ${{ env.TEST_TAG }}

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        uses: plexsystems/container-structure-test-action@v0.2.0
        with:
            image: ${{ env.TEST_TAG }}
            config: docker/container-structure-test.yaml

  setup_publish:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.RELEASE_VERSION }}
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Get Version
        id: version
        run: echo "::set-output name=RELEASE_VERSION::$(cat VERSION)"

  publish:
    if: github.event != 'pr'
    runs-on: ubuntu-latest
    needs: [build, test, setup_publish]
    steps:
      - name: Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: |
            zeekurity/zeek:latest
            zeekurity/zeek:${{ needs.setup_publish.outputs.version }}
