name: Run tests on Docker image

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - name: Build container
        uses: docker/build-push-action@v2
        id: build
        with:
          context: .
          file: docker/Dockerfile
          push: false
      - name: Run tests
        uses: plexsystems/container-structure-test-action@v0.2.0
        with:
            image: ${{ steps.build.outputs.digest }}
            config: docker/container-structure-test.yaml
