name: Run tests on Docker image

on: [pull_request]

env:
  TEST_TAG: zeek:latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - name: Build container
        uses: docker/build-push-action@v2
        id: build
        with:
          context: .
          file: docker/Dockerfile
          load: true
          tags: ${{ env.TEST_TAG }}
      - name: Run tests
        uses: plexsystems/container-structure-test-action@v0.2.0
        with:
            image: ${{ env.TEST_TAG }}
            config: docker/container-structure-test.yaml
