name: Check and publish Docker images

on:
  pull_request:
  push:
    branches: [master]
    tags:
      - 'v*'
      - '!v*-dev'
      - 'release'

defaults:
  run:
    shell: bash

env:
  TEST_TAG: zeek:latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      # Create and boot a loader. This will e.g., provide caching
      # so we avoid rebuilds of the same image after this step.
      - uses: docker/setup-buildx-action@v1
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: docker/Dockerfile
          # Load and tag the image so it can be used by the `test` job below.
          load: true
          tags: ${{ env.TEST_TAG }}

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        uses: plexsystems/container-structure-test-action@v0.2.0
        with:
            image: ${{ env.TEST_TAG }}
            config: docker/container-structure-test.yaml

  publish:
    if: github.event == 'push'
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - uses: actions/checkout@v2
      - name: Get Version
        id: version
        run: echo "::set-output name=RELEASE_VERSION::$(cat VERSION)"
      - name: Compute target tag
        id: target
        run: |
          if [ ${{ github.event.push.ref }} = "refs/tags/release" ]; then
            echo "set-output name=tag::zeek:latest"
            exit
          fi
          if [ ${{ github.event.push.ref }} = "refs/heads/main" ]; then
            echo "set-output name=tag::zeek-dev:latest"
            exit
          fi
          if [[ ${{ github.event.push.ref }} = refs/heads/v* ]] && [[ ${{ github.event.push.ref }} != refs/heads/v*-dev ]]; then
            echo "set-output name=tag::zeek:${{ steps.version.RELEASE_VERSION }}"
            exit
          fi

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push
        if: steps.target.tag != ''
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: |
            zeekurity/${{ steps.target.tag}}
